[package]
name = "netflix-challenge"
version = "0.1.0"
authors = ["Arpan <arpanghoshal3@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"
num_cpus = "1.0"
rayon = "1.5"
